export const orders = [
    {
      id: 1,
      name: "Tony Reichert",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
      products: "tony.reichert@example.com",
    },
    {
      id: 2,
      name: "Zoey Lang",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "canceled",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
      products: "zoey.lang@example.com",
    },
    {
      id: 3,
      name: "Jane Fisher",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
      products: "jane.fisher@example.com",
    },
    {
      id: 4,
      name: "William Howard",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
      products: "william.howard@example.com",
    },
    {
      id: 5,
      name: "Kristen Copper",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
      products: "kristen.cooper@example.com",
    },
    {
      id: 6,
      name: "Brian Kim",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
      products: "brian.kim@example.com",
      status: "canceled",
    },
    {
      id: 7,
      name: "Michael Hunt",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
      products: "michael.hunt@example.com",
    },
    {
      id: 8,
      name: "Samantha Brooks",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
      products: "samantha.brooks@example.com",
    },
    {
      id: 9,
      name: "Frank Harrison",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?img=4",
      products: "frank.harrison@example.com",
    },
    {
      id: 10,
      name: "Emma Adams",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=5",
      products: "emma.adams@example.com",
    },
    {
      id: 11,
      name: "Brandon Stevens",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=8",
      products: "brandon.stevens@example.com",
    },
    {
      id: 12,
      name: "Megan Richards",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?img=10",
      products: "megan.richards@example.com",
    },
    {
      id: 13,
      name: "Oliver Scott",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=12",
      products: "oliver.scott@example.com",
    },
    {
      id: 14,
      name: "Grace Allen",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=16",
      products: "grace.allen@example.com",
    },
    {
      id: 15,
      name: "Noah Carter",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?img=15",
      products: "noah.carter@example.com",
    },
    {
      id: 16,
      name: "Ava Perez",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=20",
      products: "ava.perez@example.com",
    },
    {
      id: 17,
      name: "Liam Johnson",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=33",
      products: "liam.johnson@example.com",
    },
    {
      id: 18,
      name: "Sophia Taylor",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=29",
      products: "sophia.taylor@example.com",
    },
    {
      id: 19,
      name: "Lucas Harris",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "pendient",
      avatar: "https://i.pravatar.cc/150?img=50",
      products: "lucas.harris@example.com",
    },
    {
      id: 20,
      name: "Mia Robinson",
      role: "USER",
      price: 23,
      date: "20 de Abril de 2024",
      username: "username",
      status: "completed",
      avatar: "https://i.pravatar.cc/150?img=45",
      products: "mia.robinson@example.com",
    },
  ];